server:
  port: 8766

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wy?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

  application:
    name: kgc-springcloud-web
  redis:
    host: localhost
    port: 6379
    #spring.redis.password=
    database: 0
    ssl: false


    pool:
      max-active: 10

      max-idle: 10

      max-wait: 600000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true

  httpclient:
    enabled: true

  fyj-springcloud-service:
    ribbon:
     NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

  client:
    config:
      feignName:
        connectTimeout: 5000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 1000
            readTimeout: 5000